# DataFrames I

In [ ]:
import pandas as pd

## Methods and Attributes between Series and DataFrames
- A **DataFrame** is a 2-dimensional table consisting of rows and columns.
- Pandas uses a `NaN` designation for cells that have a missing value. It is short for "not a number". Most operations on `NaN` values will produce `NaN` values.
- Like with a **Series**, Pandas assigns an index position/label to each **DataFrame** row.
- The **DataFrame** and **Series** have common and exclusive methods/attributes.
- The `hasnans` attribute exists only a **Series**. The `columns` attribute exists only on a **DataFrame**.
- Some methods/attributes will return different types of data.
- The `info` method returns a summary of the pandas object.

In [ ]:
nba = pd.read_csv("nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
nba.head()
nba.head(n=7)
nba.head(2)

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0

In [ ]:
nba.tail()
nba.tail(n=10)
nba.tail(3)

,Name,Team,Position,Height,Weight,College,Salary
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
nba.index

RangeIndex(start=0, stop=592, step=1)

In [ ]:
s.columns

AttributeError: 'Series' object has no attribute 'columns'

In [ ]:
nba.columns

Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='object')

In [ ]:
s.values

array([1, 2, 3, 4, 5])

In [ ]:
nba.values

array([['Saddiq Bey', 'Atlanta Hawks', 'F', ..., 215.0, 'Villanova',
        4556983.0],
       ['Bogdan Bogdanovic', 'Atlanta Hawks', 'G', ..., 225.0,
        'Fenerbahce', 18700000.0],
       ['Kobe Bufkin', 'Atlanta Hawks', 'G', ..., 195.0, 'Michigan',
        4094244.0],
       ...,
       ['Tristan Vukcevic', 'Washington Wizards', 'F', ..., 220.0,
        'Real Madrid', nan],
       ['Delon Wright', 'Washington Wizards', 'G', ..., 185.0, 'Utah',
        8195122.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [ ]:
s.shape

(5,)

In [ ]:
nba.shape

(592, 7)

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
type(nba)

pandas.core.frame.DataFrame

In [ ]:
s.dtypes

dtype('int64')

In [ ]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [ ]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s.hasnans
# nba.hasnans

False

In [ ]:
t = pd.Series([2,3,None])
print(t)

0    2.0
1    3.0
2    NaN
dtype: float64

In [ ]:
t.hasnans

True

In [ ]:
nba.columns
# s.columns

Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='object')

In [ ]:
s.axes

[RangeIndex(start=0, stop=5, step=1)]

In [ ]:
nba.axes

[RangeIndex(start=0, stop=592, step=1),
 Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='object')]

In [ ]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
nba.sample(4)

,Name,Team,Position,Height,Weight,College,Salary
37,Mikal Bridges,Brooklyn Nets,G-F,6-6,209.0,Villanova,21700000.0
319,MarJon Beauchamp,Milwaukee Bucks,F,6-7,199.0,NBA G League Ignite,2609400.0
579,Anthony Gill,Washington Wizards,F,6-8,230.0,Virginia,1997238.0
519,Sandro Mamukelashvili,San Antonio Spurs,F-C,6-10,240.0,Seton Hall,2019706.0

In [ ]:
nba.axes

[RangeIndex(start=0, stop=592, step=1),
 Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='object')]

In [ ]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [ ]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
dtypes: float64(2), object(5)
memory usage: 32.5+ KB

In [ ]:
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Differences between Shared Methods
- The `sum` method adds a **Series's** values.
- On a **DataFrame**, the `sum` method defaults to adding the values by traversing the index (row values).
- The `axis` parameter customizes the direction that we add across. Pass `"columns"` or `1` to add "across" the columns.

In [ ]:
import pandas as pd

In [ ]:
revenue = pd.read_csv("revenue.csv")
revenue

      Date  New York  Los Angeles  Miami
0   1/1/26       985          122    499
1   1/2/26       738          788    534
2   1/3/26        14           20    933
3   1/4/26       730          904    885
4   1/5/26       114           71    253
5   1/6/26       936          502    497
6   1/7/26       123          996    115
7   1/8/26       935          492    886
8   1/9/26       846          954    823
9  1/10/26        54          285    216

In [ ]:
s = pd.Series([1, 2, 3])
s.sum()

np.int64(6)

In [ ]:
revenue.dtypes

Date           object
New York        int64
Los Angeles     int64
Miami           int64
dtype: object

In [ ]:
revenue.shape

(10, 4)

In [ ]:
revenue.sum()

Date           1/1/261/2/261/3/261/4/261/5/261/6/261/7/261/8/...
New York                                                    5475
Los Angeles                                                 5134
Miami                                                       5641
dtype: object

In [ ]:
revenue.sum(numeric_only=True)

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [ ]:
revenue

      Date  New York  Los Angeles  Miami
0   1/1/26       985          122    499
1   1/2/26       738          788    534
2   1/3/26        14           20    933
3   1/4/26       730          904    885
4   1/5/26       114           71    253
5   1/6/26       936          502    497
6   1/7/26       123          996    115
7   1/8/26       935          492    886
8   1/9/26       846          954    823
9  1/10/26        54          285    216

In [ ]:
revenue.dtypes

Date           object
New York        int64
Los Angeles     int64
Miami           int64
dtype: object

In [ ]:
revenue.sum(axis="index")

Date           1/1/261/2/261/3/261/4/261/5/261/6/261/7/261/8/...
New York                                                    5475
Los Angeles                                                 5134
Miami                                                       5641
dtype: object

In [ ]:
revenue.sum(numeric_only = True, axis="columns")

0    1606
1    2060
2     967
3    2519
4     438
5    1935
6    1234
7    2313
8    2623
9     555
dtype: int64

In [ ]:
revenue.sum(numeric_only = True, axis="columns").sum()

np.int64(16250)

## Select One Column from a DataFrame
- We can use attribute syntax (`df.column_name`) to select a column from a **DataFrame**. The syntax will not work if the column name has spaces.
- We can also use square bracket syntax (`df["column name"]`) which will work for any column name.
- Pandas extracts a column from a **DataFrame** as a **Series**.
- The **Series** is a view, so changes to the **Series** *will* affect the **DataFrame**.
- Pandas will display a warning if you mutate the **Series**. Use the `copy` method to create a duplicate.

In [ ]:
import pandas as pd

In [ ]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
nba.Team
nba.Salary
nba.Name
# nba.name
type(nba.Name)

pandas.core.series.Series

In [ ]:
nba['Team']

0           Atlanta Hawks
1           Atlanta Hawks
2           Atlanta Hawks
3           Atlanta Hawks
4           Atlanta Hawks
              ...
587    Washington Wizards
588    Washington Wizards
589    Washington Wizards
590    Washington Wizards
591                   NaN
Name: Team, Length: 592, dtype: object

In [ ]:
print(nba["Team"])
print(nba["Salary"])

0           Atlanta Hawks
1           Atlanta Hawks
2           Atlanta Hawks
3           Atlanta Hawks
4           Atlanta Hawks
              ...
587    Washington Wizards
588    Washington Wizards
589    Washington Wizards
590    Washington Wizards
591                   NaN
Name: Team, Length: 592, dtype: object
0       4556983.0
1      18700000.0
2       4094244.0
3      20616000.0
4       2581522.0
          ...
587     1719864.0
588    10250000.0
589           NaN
590     8195122.0
591           NaN
Name: Salary, Length: 592, dtype: float64

In [ ]:
names = nba["Name"].copy()
names

0             Saddiq Bey
1      Bogdan Bogdanovic
2            Kobe Bufkin
3           Clint Capela
4         Bruno Fernando
             ...
587         Ryan Rollins
588        Landry Shamet
589     Tristan Vukcevic
590         Delon Wright
591                  NaN
Name: Name, Length: 592, dtype: object

In [ ]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
names

0             Saddiq Bey
1      Bogdan Bogdanovic
2            Kobe Bufkin
3           Clint Capela
4         Bruno Fernando
             ...
587         Ryan Rollins
588        Landry Shamet
589     Tristan Vukcevic
590         Delon Wright
591                  NaN
Name: Name, Length: 592, dtype: object

In [ ]:
names.iloc[0] = "Rajesh Hamal"

In [ ]:
names.head()

0         Rajesh Hamal
1    Bogdan Bogdanovic
2          Kobe Bufkin
3         Clint Capela
4       Bruno Fernando
Name: Name, dtype: object

In [ ]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

## Select Multiple Columns from a DataFrame
- Use square brackets with a list of names to extract multiple **DataFrame** columns.
- Pandas stores the result in a new **DataFrame** (a copy).

In [ ]:
import pandas as pd

In [ ]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
type(nba['Name'])

pandas.core.series.Series

In [ ]:
type(nba[['Name']])

pandas.core.frame.DataFrame

In [ ]:
nba[["Name", "Team"]]

                  Name                Team
0           Saddiq Bey       Atlanta Hawks
1    Bogdan Bogdanovic       Atlanta Hawks
2          Kobe Bufkin       Atlanta Hawks
3         Clint Capela       Atlanta Hawks
4       Bruno Fernando       Atlanta Hawks
..                 ...                 ...
587       Ryan Rollins  Washington Wizards
588      Landry Shamet  Washington Wizards
589   Tristan Vukcevic  Washington Wizards
590       Delon Wright  Washington Wizards
591                NaN                 NaN

[592 rows x 2 columns]

In [ ]:
nba[["Team", "Name"]]
nba[["Salary", "Name", "Team"]]

         Salary               Name                Team
0     4556983.0         Saddiq Bey       Atlanta Hawks
1    18700000.0  Bogdan Bogdanovic       Atlanta Hawks
2     4094244.0        Kobe Bufkin       Atlanta Hawks
3    20616000.0       Clint Capela       Atlanta Hawks
4     2581522.0     Bruno Fernando       Atlanta Hawks
..          ...                ...                 ...
587   1719864.0       Ryan Rollins  Washington Wizards
588  10250000.0      Landry Shamet  Washington Wizards
589         NaN   Tristan Vukcevic  Washington Wizards
590   8195122.0       Delon Wright  Washington Wizards
591         NaN                NaN                 NaN

[592 rows x 3 columns]

In [ ]:
columns_to_select = ["Name","Height","Weight"]
nba[columns_to_select]

                  Name Height  Weight
0           Saddiq Bey    6-7   215.0
1    Bogdan Bogdanovic    6-5   225.0
2          Kobe Bufkin    6-5   195.0
3         Clint Capela   6-10   256.0
4       Bruno Fernando   6-10   240.0
..                 ...    ...     ...
587       Ryan Rollins    6-3   180.0
588      Landry Shamet    6-4   190.0
589   Tristan Vukcevic   6-10   220.0
590       Delon Wright    6-5   185.0
591                NaN    NaN     NaN

[592 rows x 3 columns]

## Add New Column to DataFrame
- Use square bracket extraction syntax with an equal sign to add a new **Series** to a **DataFrame**.
- The `insert` method allows us to insert an element at a specific column index.
- On the right-hand side, we can reference an existing **DataFrame** column and perform a broadcasting operation on it to create the new **Series**.

In [ ]:
import pandas as pd

In [ ]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
nba['Name']

0             Saddiq Bey
1      Bogdan Bogdanovic
2            Kobe Bufkin
3           Clint Capela
4         Bruno Fernando
             ...
587         Ryan Rollins
588        Landry Shamet
589     Tristan Vukcevic
590         Delon Wright
591                  NaN
Name: Name, Length: 592, dtype: object

In [ ]:
nba['Sport']

KeyError: 'Sport'

In [ ]:
nba["Sport"] = "Basketball"

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Sport
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,Basketball
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,Basketball
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,Basketball
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,Basketball
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,Basketball
...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,Basketball
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,Basketball
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,Basketball
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,Basketball
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball

In [ ]:
nba.insert(loc=3, column="Type", value="Indoor")

In [ ]:
nba

,Name,Team,Position,Type,Height,Weight,College,Salary,Sport
0,Saddiq Bey,Atlanta Hawks,F,Indoor,6-7,215.0,Villanova,4556983.0,Basketball
1,Bogdan Bogdanovic,Atlanta Hawks,G,Indoor,6-5,225.0,Fenerbahce,18700000.0,Basketball
2,Kobe Bufkin,Atlanta Hawks,G,Indoor,6-5,195.0,Michigan,4094244.0,Basketball
3,Clint Capela,Atlanta Hawks,C,Indoor,6-10,256.0,Elan Chalon,20616000.0,Basketball
4,Bruno Fernando,Atlanta Hawks,F-C,Indoor,6-10,240.0,Maryland,2581522.0,Basketball
...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,Indoor,6-3,180.0,Toledo,1719864.0,Basketball
588,Landry Shamet,Washington Wizards,G,Indoor,6-4,190.0,Wichita State,10250000.0,Basketball
589,Tristan Vukcevic,Washington Wizards,F,Indoor,6-10,220.0,Real Madrid,NaN,Basketball
590,Delon Wright,Washington Wizards,G,Indoor,6-5,185.0,Utah,8195122.0,Basketball
591,NaN,NaN,NaN,Indoor,NaN,NaN,NaN,NaN,Basketball

In [ ]:
nba["Salary"] * 2
nba["Salary"].mul(2)

nba["Salary Doubled"] = nba["Salary"].mul(2)

In [ ]:
nba

,Name,Team,Position,Type,Height,Weight,College,Salary,Sport,Salary Doubled
0,Saddiq Bey,Atlanta Hawks,F,Indoor,6-7,215.0,Villanova,4556983.0,Basketball,9113966.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,Indoor,6-5,225.0,Fenerbahce,18700000.0,Basketball,37400000.0
2,Kobe Bufkin,Atlanta Hawks,G,Indoor,6-5,195.0,Michigan,4094244.0,Basketball,8188488.0
3,Clint Capela,Atlanta Hawks,C,Indoor,6-10,256.0,Elan Chalon,20616000.0,Basketball,41232000.0
4,Bruno Fernando,Atlanta Hawks,F-C,Indoor,6-10,240.0,Maryland,2581522.0,Basketball,5163044.0
...,...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,Indoor,6-3,180.0,Toledo,1719864.0,Basketball,3439728.0
588,Landry Shamet,Washington Wizards,G,Indoor,6-4,190.0,Wichita State,10250000.0,Basketball,20500000.0
589,Tristan Vukcevic,Washington Wizards,F,Indoor,6-10,220.0,Real Madrid,NaN,Basketball,NaN
590,Delon Wright,Washington Wizards,G,Indoor,6-5,185.0,Utah,8195122.0,Basketball,16390244.0
591,NaN,NaN,NaN,Indoor,NaN,NaN,NaN,NaN,Basketball,NaN

In [ ]:
nba.Team

0           Atlanta Hawks
1           Atlanta Hawks
2           Atlanta Hawks
3           Atlanta Hawks
4           Atlanta Hawks
              ...
587    Washington Wizards
588    Washington Wizards
589    Washington Wizards
590    Washington Wizards
591                   NaN
Name: Team, Length: 592, dtype: object

In [ ]:
nba['Team']

0           Atlanta Hawks
1           Atlanta Hawks
2           Atlanta Hawks
3           Atlanta Hawks
4           Atlanta Hawks
              ...
587    Washington Wizards
588    Washington Wizards
589    Washington Wizards
590    Washington Wizards
591                   NaN
Name: Team, Length: 592, dtype: object

In [ ]:
nba.Salary Doubled

SyntaxError: invalid syntax (2972677689.py, line 1)

In [ ]:
nba['Salary Doubled']

0       9113966.0
1      37400000.0
2       8188488.0
3      41232000.0
4       5163044.0
          ...
587     3439728.0
588    20500000.0
589           NaN
590    16390244.0
591           NaN
Name: Salary Doubled, Length: 592, dtype: float64

In [ ]:
nba["Salary"] - 50000
s = nba["Salary"].sub(50000)

nba.insert(loc = 8, column = "50000 subtracted from initial salary", value = s)

In [ ]:
nba

,Name,Team,Position,Type,Height,Weight,College,Salary,50000 subtracted from initial salary,Sport,Salary Doubled
0,Saddiq Bey,Atlanta Hawks,F,Indoor,6-7,215.0,Villanova,4556983.0,4506983.0,Basketball,9113966.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,Indoor,6-5,225.0,Fenerbahce,18700000.0,18650000.0,Basketball,37400000.0
2,Kobe Bufkin,Atlanta Hawks,G,Indoor,6-5,195.0,Michigan,4094244.0,4044244.0,Basketball,8188488.0
3,Clint Capela,Atlanta Hawks,C,Indoor,6-10,256.0,Elan Chalon,20616000.0,20566000.0,Basketball,41232000.0
4,Bruno Fernando,Atlanta Hawks,F-C,Indoor,6-10,240.0,Maryland,2581522.0,2531522.0,Basketball,5163044.0
...,...,...,...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,Indoor,6-3,180.0,Toledo,1719864.0,1669864.0,Basketball,3439728.0
588,Landry Shamet,Washington Wizards,G,Indoor,6-4,190.0,Wichita State,10250000.0,10200000.0,Basketball,20500000.0
589,Tristan Vukcevic,Washington Wizards,F,Indoor,6-10,220.0,Real Madrid,NaN,NaN,Basketball,NaN
590,Delon Wright,Washington Wizards,G,Indoor,6-5,185.0,Utah,8195122.0,8145122.0,Basketball,16390244.0
591,NaN,NaN,NaN,Indoor,NaN,NaN,NaN,NaN,NaN,Basketball,NaN

In [ ]:
l = [1,2,3,4]

In [ ]:
l[::-1]

[4, 3, 2, 1]

In [ ]:
l

[1, 2, 3, 4]

In [ ]:
l.reverse()

In [ ]:
l

[4, 3, 2, 1]

## A Review of the value_counts Method
- The `value_counts` method counts the number of times that each unique value occurs in a **Series**.

In [ ]:
import pandas as pd

In [ ]:
nba = pd.read_csv("nba.csv")
nba.sample(5)

,Name,Team,Position,Height,Weight,College,Salary
470,Ish Wainright,Phoenix Suns,F,6-5,250.0,Baylor,NaN
317,Thanasis Antetokounmpo,Milwaukee Bucks,F,6-7,219.0,Panathinaikos,2346614.0
175,Stephen Curry,Golden State Warriors,G,6-2,185.0,Davidson,51915615.0
558,Johnny Juzang,Utah Jazz,G,6-6,209.0,UCLA,559782.0
476,Jerami Grant,Portland Trail Blazers,F,6-8,210.0,Syracuse,27586207.0

In [ ]:
nba.value_counts(ascending=False)

Name              Team                  Position  Height  Weight  College        Salary
Zion Williamson   New Orleans Pelicans  F         6-6     284.0   Duke           34005250.0    1
AJ Green          Milwaukee Bucks       G         6-5     190.0   Northern Iowa  1901769.0     1
AJ Griffin        Atlanta Hawks         F         6-6     220.0   Duke           3712920.0     1
Aaron Gordon      Denver Nuggets        F         6-8     235.0   Arizona        22266182.0    1
Aaron Holiday     Houston Rockets       G         6-0     185.0   UCLA           2346614.0     1
                                                                                              ..
Amari Bailey      Charlotte Hornets     G         6-5     185.0   UCLA           559782.0      1
Alperen Sengun    Houston Rockets       C         6-11    243.0   Besiktas       3536280.0     1
Alondes Williams  Miami Heat            G         6-4     210.0   Wake Forest    1801769.0     1
Alex Len          Sacramento Kings      C         7-2     250.0   Maryland       3196448.0     1
Alex Fudge        Los Angeles Lakers    F         6-9     200.0   Florida        559782.0      1
Name: count, Length: 475, dtype: int64

In [ ]:
nba["Team"].value_counts()

Team
Dallas Mavericks          23
Denver Nuggets            22
Miami Heat                22
Milwaukee Bucks           22
Memphis Grizzlies         22
Indiana Pacers            21
Philadelphia 76ers        21
Washington Wizards        21
Utah Jazz                 21
Oklahoma City Thunder     21
New York Knicks           21
Toronto Raptors           21
Charlotte Hornets         20
Houston Rockets           20
San Antonio Spurs         20
Phoenix Suns              20
Chicago Bulls             19
Minnesota Timberwolves    19
Cleveland Cavaliers       19
Los Angeles Lakers        19
Detroit Pistons           19
Los Angeles Clippers      19
Sacramento Kings          18
Orlando Magic             18
Boston Celtics            18
Atlanta Hawks             18
Golden State Warriors     17
Brooklyn Nets             17
Portland Trail Blazers    17
New Orleans Pelicans      16
Name: count, dtype: int64

In [ ]:
nba['Name'].value_counts()

Name
Delon Wright         1
Saddiq Bey           1
Bogdan Bogdanovic    1
Kobe Bufkin          1
Clint Capela         1
                    ..
Oshae Brissett       1
Dalano Banton        1
Trae Young           1
Onyeka Okongwu       1
Miles Norris         1
Name: count, Length: 591, dtype: int64

In [ ]:
nba["Position"].value_counts()
nba["Position"].value_counts(normalize=True)
nba["Position"].value_counts(normalize=True) * 100

Position
G      39.212329
F      32.020548
C       8.047945
G-F     7.876712
F-C     6.335616
C-F     3.938356
F-G     2.568493
Name: proportion, dtype: float64

In [ ]:
nba["Salary"].value_counts()
nba["Salary"].value_counts(ascending=True)
nba["Salary"].value_counts(normalize=True)
nba["Salary"].value_counts(normalize=True) * 100

Salary
559782.0      12.090164
1119563.0      5.532787
3196448.0      2.663934
2019706.0      1.844262
1719864.0      1.639344
                ...
2581522.0      0.204918
20616000.0     0.204918
4094244.0      0.204918
18700000.0     0.204918
4556983.0      0.204918
Name: proportion, Length: 298, dtype: float64

## Drop Rows with Missing Values
- Pandas uses a `NaN` designation for cells that have a missing value.
- The `dropna` method deletes rows with missing values. Its default behavior is to remove a row if it has *any* missing values.
- Pass the `how` parameter an argument of "all" to delete rows where all the values are `NaN`.
- The `subset` parameters customizes/limits the columns that pandas will use to drop rows with missing values.

In [ ]:
import pandas as pd

In [ ]:
nba = pd.read_csv("nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.sample(10)

,Name,Team,Position,Height,Weight,College,Salary
25,Al Horford,Boston Celtics,C-F,6-9,240.0,Florida,10000000.0
535,Javon Freeman-Liberty,Toronto Raptors,G,6-4,180.0,DePaul,NaN
109,Max Strus,Cleveland Cavaliers,G-F,6-5,215.0,DePaul,14487684.0
161,Cade Cunningham,Detroit Pistons,G,6-7,220.0,Oklahoma State,11055360.0
21,Jaylen Brown,Boston Celtics,G-F,6-6,223.0,California,31830357.0
196,Jeff Green,Houston Rockets,F,6-8,235.0,Georgetown,9600000.0
546,Garrett Temple,Toronto Raptors,G-F,6-6,195.0,Louisiana State,3196448.0
496,Colby Jones,Sacramento Kings,G,6-6,207.0,Xavier,2019706.0
260,Jalen Hood-Schifino,Los Angeles Lakers,G,6-6,215.0,Indiana,3695076.0
336,Lindell Wigginton,Milwaukee Bucks,G,6-1,189.0,Iowa State,559782.0

In [ ]:
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.isna()

      Name   Team  Position  Height  Weight  College  Salary
0    False  False     False   False   False    False   False
1    False  False     False   False   False    False   False
2    False  False     False   False   False    False   False
3    False  False     False   False   False    False   False
4    False  False     False   False   False    False   False
..     ...    ...       ...     ...     ...      ...     ...
587  False  False     False   False   False    False   False
588  False  False     False   False   False    False   False
589  False  False     False   False   False    False    True
590  False  False     False   False   False    False   False
591   True   True      True    True    True     True    True

[592 rows x 7 columns]

In [ ]:
nba.isna().sum()

Name          1
Team          1
Position      8
Height        7
Weight        8
College      14
Salary      104
dtype: int64

In [ ]:
nba.isnull()
nba.isnull().sum()

Name          1
Team          1
Position      8
Height        7
Weight        8
College      14
Salary      104
dtype: int64

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.dropna() # drop all the rows having missing values
nba.dropna(how="any")

nba.dropna(how="all")

nba.dropna(subset=["College"])
nba.dropna(subset=["College", "Salary"])

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [ ]:
592 - 476

116

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Fill in Missing Values with the fillna Method
- The `fillna` method replaces missing `NaN` values with its argument.
- The `fillna` method is available on both **DataFrames** and **Series**.
- An extracted **Series** is a view on the original **DataFrame**, but the `fillna` method returns a copy.

In [ ]:
import pandas as pd

In [ ]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [ ]:
nba.fillna(0)

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [ ]:
nba.isna().sum()

Name          0
Team          0
Position      7
Height        6
Weight        7
College      13
Salary      103
dtype: int64

In [ ]:
nba['Salary'].isnull().sum()

np.int64(103)

In [ ]:
# nba['Salary'].fillna(0, inplace = True)
nba["Salary"] = nba["Salary"].fillna(0)

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [ ]:
nba['Salary'].isnull().sum()

np.int64(0)

In [ ]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    591 non-null    float64
dtypes: float64(2), object(5)
memory usage: 36.9+ KB

In [ ]:
nba['College'].isna().sum()

np.int64(13)

In [ ]:
nba.isnull().sum()

Name         0
Team         0
Position     7
Height       6
Weight       7
College     13
Salary       0
dtype: int64

In [ ]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [ ]:
nba["College"] = nba["College"].fillna(value="Unknown")

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [ ]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [ ]:
nba['College'].isnull().sum()

np.int64(0)

In [ ]:
type(nba)

pandas.core.frame.DataFrame

In [ ]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

## The astype Method I
- The `astype` method converts a **Series's** values to a specified type.
- Pass in the specified type as either a string or the core Python data type.
- Pandas cannot convert `NaN` values to numeric types, so we need to eliminate/replace them before we perform the conversion.
- The `dtypes` attribute returns a **Series** with the **DataFrame's** columns and their types.

In [ ]:
import pandas as pd

In [ ]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    584 non-null    float64
 5   College   578 non-null    object
 6   Salary    488 non-null    float64
dtypes: float64(2), object(5)
memory usage: 36.9+ KB

In [ ]:
nba["Salary"] = nba["Salary"].fillna(0)
nba["Weight"] = nba["Weight"].fillna(0)
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [ ]:
nba['Salary'].isnull().sum()

np.int64(0)

In [ ]:
nba['Weight'].isnull().sum()

np.int64(0)

In [ ]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [ ]:
nba.head(30)

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
5,Trent Forrest,Atlanta Hawks,G,6-4,210.0,Florida State,508891.0
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
7,Mouhamed Gueye,Atlanta Hawks,F,6-11,210.0,Washington State,1119563.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0
9,Jalen Johnson,Atlanta Hawks,F,6-8,219.0,Duke,2925360.0
10,Seth Lundy,Atlanta Hawks,G,6-6,220.0,Penn State,559782.0
11,Garrison Mathews,Atlanta Hawks,G,6-6,215.0,Lipscomb,2000000.0
12,Wesley Matthews,Atlanta Hawks,G,6-5,220.0,Marquette,3196448.0
13,Patty Mills,Atlanta Hawks,G,6-0,180.0,St. Mary's,6802950.0
14,Dejounte Murray,Atlanta Hawks,G,6-5,180.0,Washington,18214000.0
15,Miles Norris,Atlanta Hawks,NaN,NaN,0.0,NaN,559782.0
16,Onyeka Okongwu,Atlanta Hawks,F-C,6-9,240.0,Southern California,8109063.0
17,Trae Young,Atlanta Hawks,G,6-1,164.0,Oklahoma,40064220.0
18,Dalano Banton,Boston Celtics,F,6-7,204.0,Nebraska,2019706.0
19,Oshae Brissett,Boston Celtics,F-G,6-7,210.0,Syracuse,2165000.0
20,Malcolm Brogdon,Boston Celtics,G,6-4,229.0,Virginia,22500000.0
21,Jaylen Brown,Boston Celtics,G-F,6-6,223.0,California,31830357.0
22,JD Davison,Boston Celtics,G,6-1,195.0,Alabama,559782.0
23,Blake Griffin,Boston Celtics,F,6-9,250.0,Oklahoma,0.0
24,Sam Hauser,Boston Celtics,F,6-7,217.0,Virginia,1927896.0
25,Al Horford,Boston Celtics,C-F,6-9,240.0,Florida,10000000.0
26,Mfiondu Kabengele,Boston Celtics,C,6-10,250.0,Florida State,0.0
27,Luke Kornet,Boston Celtics,C-F,7-2,250.0,Vanderbilt,2413304.0
28,Svi Mykhailiuk,Boston Celtics,G-F,6-7,205.0,Kansas,0.0
29,Kristaps Porzingis,Boston Celtics,F-C,7-3,240.0,Cajasol Sevilla,36016200.0

In [ ]:
nba.dtypes

Name         object
Team         object
Position     object
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [ ]:
nba["Salary"].astype("int")
nba["Salary"].astype(int)

nba["Salary"] = nba["Salary"].astype(int)

In [ ]:
nba["Weight"] = nba["Weight"].astype(int)

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215,Villanova,4556983
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225,Fenerbahce,18700000
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195,Michigan,4094244
3,Clint Capela,Atlanta Hawks,C,6-10,256,Elan Chalon,20616000
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240,Maryland,2581522
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194,Michigan,27955357
587,Ryan Rollins,Washington Wizards,G,6-3,180,Toledo,1719864
588,Landry Shamet,Washington Wizards,G,6-4,190,Wichita State,10250000
589,Tristan Vukcevic,Washington Wizards,F,6-10,220,Real Madrid,0
590,Delon Wright,Washington Wizards,G,6-5,185,Utah,8195122

In [ ]:
nba.dtypes

Name        object
Team        object
Position    object
Height      object
Weight       int64
College     object
Salary       int64
dtype: object

## The astype Method II
- The `category` type is ideal for columns with a limited number of unique values.
- The `nunique` method will return a **Series** with the number of unique values in each column.
- With categories, pandas does not create a separate value in memory for each "cell". Rather, the cells point to a single copy for each unique value.

In [ ]:
# nba = pd.read_csv("nba.csv").dropna(how ="all")
# nba.tail()

In [ ]:
nba['Team'].unique()

array(['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets',
       'Charlotte Hornets', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Dallas Mavericks', 'Denver Nuggets', 'Detroit Pistons',
       'Golden State Warriors', 'Houston Rockets', 'Indiana Pacers',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Memphis Grizzlies',
       'Miami Heat', 'Milwaukee Bucks', 'Minnesota Timberwolves',
       'New Orleans Pelicans', 'New York Knicks', 'Oklahoma City Thunder',
       'Orlando Magic', 'Philadelphia 76ers', 'Phoenix Suns',
       'Portland Trail Blazers', 'Sacramento Kings', 'San Antonio Spurs',
       'Toronto Raptors', 'Utah Jazz', 'Washington Wizards'], dtype=object)

In [ ]:
nba['Team'].nunique()

30

In [ ]:
nba.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:
nba.nunique()

Name        591
Team         30
Position      7
Height       20
Weight       94
College     182
Salary      299
dtype: int64

In [ ]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    object
 2   Position  584 non-null    object
 3   Height    585 non-null    object
 4   Weight    591 non-null    int64
 5   College   578 non-null    object
 6   Salary    591 non-null    int64
dtypes: int64(2), object(5)
memory usage: 36.9+ KB

In [ ]:
nba["Position"] = nba["Position"].astype("category")

In [ ]:
nba["Team"] = nba["Team"].astype("category")

In [ ]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    object
 1   Team      591 non-null    category
 2   Position  584 non-null    category
 3   Height    585 non-null    object
 4   Weight    591 non-null    int64
 5   College   578 non-null    object
 6   Salary    591 non-null    int64
dtypes: category(2), int64(2), object(3)
memory usage: 30.5+ KB

In [ ]:
(36.9 - 30.5) / 36.9 * 100

17.344173441734416

## Sort a DataFrame with the sort_values Method I
- The `sort_values` method sorts a **DataFrame** by the values in one or more columns. The default sort is an ascending one (alphabetical for strings).
- The first parameter (`by`) expects the column(s) to sort by.
- If sorting by a single column, pass a string with its name.
- The `ascending` parameter customizes the sort order.
- The `na_position` parameter customizes where pandas places `NaN` values.

In [ ]:
nba = pd.read_csv("nba.csv")
nba.tail()

,Name,Team,Position,Height,Weight,College,Salary
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.sort_values("Name")

,Name,Team,Position,Height,Weight,College,Salary
122,A.J. Lawson,Dallas Mavericks,G,6-6,179.0,South Carolina,NaN
324,AJ Green,Milwaukee Bucks,G,6-5,190.0,Northern Iowa,1901769.0
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
141,Aaron Gordon,Denver Nuggets,F,6-8,235.0,Arizona,22266182.0
198,Aaron Holiday,Houston Rockets,G,6-0,185.0,UCLA,2346614.0
...,...,...,...,...,...,...,...
83,Zach LaVine,Chicago Bulls,G,6-5,200.0,UCLA,40064220.0
149,Zeke Nnaji,Denver Nuggets,F-C,6-9,240.0,Arizona,4306281.0
291,Ziaire Williams,Memphis Grizzlies,F,6-9,185.0,Stanford,4810200.0
370,Zion Williamson,New Orleans Pelicans,F,6-6,284.0,Duke,34005250.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.sort_values(by="Team")

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
17,Trae Young,Atlanta Hawks,G,6-1,164.0,Oklahoma,40064220.0
16,Onyeka Okongwu,Atlanta Hawks,F-C,6-9,240.0,Southern California,8109063.0
15,Miles Norris,Atlanta Hawks,NaN,NaN,NaN,NaN,559782.0
14,Dejounte Murray,Atlanta Hawks,G,6-5,180.0,Washington,18214000.0
...,...,...,...,...,...,...,...
570,Deni Avdija,Washington Wizards,F,6-9,210.0,Maccabi Tel Aviv,6263188.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
579,Anthony Gill,Washington Wizards,F,6-8,230.0,Virginia,1997238.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.sort_values(by="Name", ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
370,Zion Williamson,New Orleans Pelicans,F,6-6,284.0,Duke,34005250.0
291,Ziaire Williams,Memphis Grizzlies,F,6-9,185.0,Stanford,4810200.0
149,Zeke Nnaji,Denver Nuggets,F-C,6-9,240.0,Arizona,4306281.0
83,Zach LaVine,Chicago Bulls,G,6-5,200.0,UCLA,40064220.0
515,Zach Collins,San Antonio Spurs,F-C,6-11,250.0,Gonzaga,7700000.0
...,...,...,...,...,...,...,...
141,Aaron Gordon,Denver Nuggets,F,6-8,235.0,Arizona,22266182.0
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
324,AJ Green,Milwaukee Bucks,G,6-5,190.0,Northern Iowa,1901769.0
122,A.J. Lawson,Dallas Mavericks,G,6-6,179.0,South Carolina,NaN
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.sort_values(by="Weight", ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
483,Jusuf Nurkic,Portland Trail Blazers,C,7-0,290.0,Cedevita,16875000.0
370,Zion Williamson,New Orleans Pelicans,F,6-6,284.0,Duke,34005250.0
145,Nikola Jokic,Denver Nuggets,C,6-11,284.0,Mega Basket,47607350.0
329,Brook Lopez,Milwaukee Bucks,C,7-1,282.0,Stanford,25000000.0
330,Robin Lopez,Milwaukee Bucks,C,7-0,281.0,Stanford,3196448.0
...,...,...,...,...,...,...,...
138,Armaan Franklin,Denver Nuggets,NaN,NaN,NaN,NaN,1119563.0
299,Caleb Daniels,Miami Heat,NaN,NaN,NaN,NaN,1119563.0
460,Toumani Camara,Phoenix Suns,F,6-8,NaN,Dayton,1119563.0
564,Nick Ongenda,Utah Jazz,NaN,NaN,NaN,NaN,1119563.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.sort_values(by="Salary", ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
175,Stephen Curry,Golden State Warriors,G,6-2,185.0,Davidson,51915615.0
461,Kevin Durant,Phoenix Suns,F,6-10,240.0,Texas,47649433.0
261,LeBron James,Los Angeles Lakers,F,6-9,250.0,St. Vincent-St. Mary HS (OH),47607350.0
436,Joel Embiid,Philadelphia 76ers,C-F,7-0,280.0,Kansas,47607350.0
145,Nikola Jokic,Denver Nuggets,C,6-11,284.0,Mega Basket,47607350.0
...,...,...,...,...,...,...,...
547,Gary Trent Jr.,Toronto Raptors,G-F,6-5,209.0,Duke,NaN
578,Taj Gibson,Washington Wizards,F,6-9,232.0,Southern California,NaN
584,Kendrick Nunn,Washington Wizards,G,6-3,190.0,Oakland,NaN
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba[nba['Name'] == 'Kobe Bryant']

Empty DataFrame
Columns: [Name, Team, Position, Height, Weight, College, Salary]
Index: []

## Sort a DataFrame with the sort_values Method II
- To sort by multiple columns, pass the `by` parameter a list of column names. Pandas will sort in the specified column order (first to last).
- Pass the `ascending` parameter a Boolean to sort all columns in a consistent order (all ascending or all descending).
- Pass `ascending` a list to customize the sort order *per* column. The `ascending` list length must match the `by` list.

In [ ]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
nba = nba.sort_values(['Team','Name'])

In [ ]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0

In [ ]:
nba.to_csv('nba1.csv')

In [ ]:
nba.to_excel('nba.xlsx')

In [ ]:
nba1 = pd.read_csv('nba1.csv', index_col='Name')

In [ ]:
nba1

,Unnamed: 0,Team,Position,Height,Weight,College,Salary
Name,,,,,,,
AJ Griffin,6,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
Bogdan Bogdanovic,1,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
Bruno Fernando,4,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
Clint Capela,3,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
De'Andre Hunter,8,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0
...,...,...,...,...,...,...,...
Taj Gibson,578,Washington Wizards,F,6-9,232.0,Southern California,NaN
Tristan Vukcevic,589,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
Tyus Jones,580,Washington Wizards,G,6-2,196.0,Duke,14000000.0
Xavier Cooks,573,Washington Wizards,F,6-8,183.0,Winthrop,1719864.0
NaN,591,NaN,NaN,NaN,NaN,NaN,NaN

## Sort a DataFrame by its Index
- The `sort_index` method sorts the **DataFrame** by its index positions/labels.

In [ ]:
import pandas as pd

In [ ]:
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0

In [ ]:
nba = nba.sort_values(["Team", "Name"])
nba

,Name,Team,Position,Height,Weight,College,Salary
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0
...,...,...,...,...,...,...,...
578,Taj Gibson,Washington Wizards,F,6-9,232.0,Southern California,NaN
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
580,Tyus Jones,Washington Wizards,G,6-2,196.0,Duke,14000000.0
573,Xavier Cooks,Washington Wizards,F,6-8,183.0,Winthrop,1719864.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.sort_index()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba.sort_index(ascending=True)
nba.sort_index(ascending=False)

,Name,Team,Position,Height,Weight,College,Salary
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
...,...,...,...,...,...,...,...
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0
...,...,...,...,...,...,...,...
578,Taj Gibson,Washington Wizards,F,6-9,232.0,Southern California,NaN
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
580,Tyus Jones,Washington Wizards,G,6-2,196.0,Duke,14000000.0
573,Xavier Cooks,Washington Wizards,F,6-8,183.0,Winthrop,1719864.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nba = nba.sort_index(ascending=False)

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
...,...,...,...,...,...,...,...
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0

## Rank Values with the rank Method
- The `rank` method assigns a numeric ranking to each **Series** value.
- Pandas will assign the same rank to equal values and create a "gap" in the dataset for the ranks.

In [ ]:
nba = pd.read_csv("nba.csv").dropna(how="all")
nba["Salary"] = nba["Salary"].fillna(0).astype(int)
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122

In [ ]:
nba["Salary"].rank()

0      361.0
1      512.0
2      349.0
3      523.0
4      284.0
       ...
586    544.0
587    197.5
588    452.0
589     52.0
590    429.0
Name: Salary, Length: 591, dtype: float64

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122

In [ ]:
nba['Salary Rank']

KeyError: 'Salary Rank'

In [ ]:
nba["Salary Rank"] = nba["Salary"].rank(ascending = False)

In [ ]:
nba

,Name,Team,Position,Height,Weight,College,Salary,Salary Rank
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983,231.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000,80.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244,243.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000,69.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522,308.0
...,...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357,48.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864,394.5
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000,140.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0,540.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122,163.0

In [ ]:
nba.sort_values("Salary", ascending=False).head(13)

,Name,Team,Position,Height,Weight,College,Salary,Salary Rank
175,Stephen Curry,Golden State Warriors,G,6-2,185.0,Davidson,51915615,1.0
461,Kevin Durant,Phoenix Suns,F,6-10,240.0,Texas,47649433,2.0
145,Nikola Jokic,Denver Nuggets,C,6-11,284.0,Mega Basket,47607350,4.0
436,Joel Embiid,Philadelphia 76ers,C-F,7-0,280.0,Kansas,47607350,4.0
261,LeBron James,Los Angeles Lakers,F,6-9,250.0,St. Vincent-St. Mary HS (OH),47607350,4.0
456,Bradley Beal,Phoenix Suns,G,6-4,207.0,Florida,46741590,6.0
316,Giannis Antetokounmpo,Milwaukee Bucks,F,7-0,243.0,Filathlitikos,45640084,8.5
239,Paul George,Los Angeles Clippers,F,6-8,220.0,Fresno State,45640084,8.5
241,Kawhi Leonard,Los Angeles Clippers,F,6-7,225.0,San Diego State,45640084,8.5
480,Damian Lillard,Portland Trail Blazers,G,6-2,195.0,Weber State,45640084,8.5
296,Jimmy Butler,Miami Heat,F,6-7,230.0,Marquette,45183960,11.0
190,Klay Thompson,Golden State Warriors,G,6-6,220.0,Washington State,43219440,12.0
344,Rudy Gobert,Minnesota Timberwolves,C,7-1,258.0,Cholet,41000000,13.0

In [ ]:
(3+4+5)/3

4.0

In [ ]:
(7+8+9+10)/4

8.5